use serde::Deserialize;
use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Manifest {
    module: Vec<Module>,
}

#[derive(Debug, Deserialize)]
struct Module {
    name: String,
    #[serde(default)]
    builtin: Vec<Platform>,
    native: Option<Vec<Platform>>,
    policy: Option<Policy>,
}

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
enum Platform {
    All,
    Unix,
    Windows,
    Other,
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Policy {
    PreferNative,
    PreferSourceWhenAvailable,
}

struct NativeEntry<'a> {
    name: &'a str,
    platform: Platform,
    policy: Policy,
}

fn main() {
    println!("cargo:rerun-if-changed=modules.toml");

    let manifest_path =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap()).join("modules.toml");
    let manifest_text = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", manifest_path.display()));
    let manifest: Manifest = toml::from_str(&manifest_text)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", manifest_path.display()));

    let generated = generate(&manifest);
    let out_path = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("stdlib_metadata.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate(manifest: &Manifest) -> String {
    validate(manifest);

    let mut builtin_windows = Vec::new();
    let mut builtin_unix = Vec::new();
    let mut builtin_other = Vec::new();
    let mut native_entries = Vec::new();

    for module in &manifest.module {
        if applies_to(&module.builtin, Platform::Windows) {
            builtin_windows.push(module.name.as_str());
        }
        if applies_to(&module.builtin, Platform::Unix) {
            builtin_unix.push(module.name.as_str());
        }
        if applies_to(&module.builtin, Platform::Other) {
            builtin_other.push(module.name.as_str());
        }

        let native_platforms = native_platforms(module);
        if let Some(policy) = module.policy {
            for platform in native_platforms {
                native_entries.push(NativeEntry {
                    name: &module.name,
                    platform,
                    policy,
                });
            }
        }
    }

    builtin_windows.sort_unstable();
    builtin_unix.sort_unstable();
    builtin_other.sort_unstable();
    native_entries.sort_unstable_by(|left, right| {
        left.name
            .cmp(right.name)
            .then_with(|| platform_name(left.platform).cmp(platform_name(right.platform)))
    });

    let mut output = String::new();
    writeln!(
        output,
        "// Generated by crates/prism_stdlib/build.rs from crates/prism_stdlib/modules.toml."
    )
    .unwrap();
    writeln!(output, "// Do not edit by hand.").unwrap();
    writeln!(output).unwrap();

    write_str_array(
        &mut output,
        "WINDOWS_BUILTIN_MODULE_NAMES",
        &builtin_windows,
    );
    write_str_array(&mut output, "UNIX_BUILTIN_MODULE_NAMES", &builtin_unix);
    write_str_array(&mut output, "OTHER_BUILTIN_MODULE_NAMES", &builtin_other);

    writeln!(output, "const NATIVE_MODULES: &[NativeModuleMetadata] = &[").unwrap();
    for entry in native_entries {
        writeln!(
            output,
            "    NativeModuleMetadata {{ name: {:?}, policy: {}, platform: {} }},",
            entry.name,
            policy_name(entry.policy),
            platform_name(entry.platform),
        )
        .unwrap();
    }
    writeln!(output, "];").unwrap();

    output
}

fn validate(manifest: &Manifest) {
    let mut seen = BTreeSet::new();
    let mut previous_name: Option<&str> = None;
    for module in &manifest.module {
        assert!(
            !module.name.trim().is_empty(),
            "stdlib module names must not be empty"
        );
        if let Some(previous_name) = previous_name {
            assert!(
                previous_name < module.name.as_str(),
                "stdlib modules must be listed in sorted order: `{previous_name}` before `{}`",
                module.name
            );
        }
        previous_name = Some(module.name.as_str());

        assert!(
            seen.insert(module.name.as_str()),
            "duplicate stdlib module `{}`",
            module.name
        );

        let native_platforms = native_platforms(module);
        assert!(
            module.policy.is_some() || native_platforms.is_empty(),
            "module `{}` declares native platforms without a policy",
            module.name
        );
        assert!(
            module.policy.is_none() || !native_platforms.is_empty(),
            "module `{}` declares a policy without native platforms",
            module.name
        );
        assert_unique_platforms(&module.name, "builtin", &module.builtin);
        assert_unique_platforms(&module.name, "native", &native_platforms);
    }
}

fn native_platforms(module: &Module) -> Vec<Platform> {
    match (&module.native, module.policy) {
        (Some(platforms), _) => platforms.clone(),
        (None, Some(_)) => vec![Platform::All],
        (None, None) => Vec::new(),
    }
}

fn assert_unique_platforms(module_name: &str, field: &str, platforms: &[Platform]) {
    let mut seen = BTreeSet::new();
    for platform in platforms {
        assert!(
            seen.insert(platform_name(*platform)),
            "module `{module_name}` declares duplicate {field} platform `{}`",
            platform_name(*platform)
        );
    }
}

fn applies_to(platforms: &[Platform], target: Platform) -> bool {
    platforms
        .iter()
        .any(|platform| *platform == Platform::All || *platform == target)
}

fn write_str_array(output: &mut String, name: &str, values: &[&str]) {
    writeln!(output, "const {name}: &[&str] = &[").unwrap();
    for value in values {
        writeln!(output, "    {value:?},").unwrap();
    }
    writeln!(output, "];").unwrap();
    writeln!(output).unwrap();
}

fn policy_name(policy: Policy) -> &'static str {
    match policy {
        Policy::PreferNative => "StdlibResolutionPolicy::PreferNative",
        Policy::PreferSourceWhenAvailable => "StdlibResolutionPolicy::PreferSourceWhenAvailable",
    }
}

fn platform_name(platform: Platform) -> &'static str {
    match platform {
        Platform::All => "StdlibPlatform::All",
        Platform::Unix => "StdlibPlatform::Unix",
        Platform::Windows => "StdlibPlatform::Windows",
        Platform::Other => "StdlibPlatform::Other",
    }
}
